include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: ignore
    prefer_const_constructors: ignore
    deprecated_member_use: ignore
    depend_on_referenced_packages: ignore
